# Generated by Django 4.2.13 on 2025-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_project_created_by_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('reviewing', 'Reviewing'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
